baseURL = "https://blog.dsb.dev"
languageCode = "en-gb"
title = "David Bond - Dishevelled Software Engineer"
theme = "cactus"
copyright = "David Bond"
googleAnalytics = "UA-46697487-4"
googleAnalyticsAsync = true
relativeURLs = true

[params]
	description = "Blog posts about the Go ecosystem, tools & packages. Right now I delete production at [HashiCorp](https://hashicorp.com). Previously, I've worked at [Jetstack](https://jetstack.io), [Utility Warehouse](https://uw.co.uk/) and [OVO Energy](https://www.ovoenergy.com/)."
	mainSection = "posts"
	rss = true
	colortheme = "white"
	logo = "images/me.jpg"
	postsOnHomePage = 20
	showProjectsList = true
	projectsUrl = "https://github.com/davidsbond"

[[params.social]]
	name = "github"
	link = "https://github.com/davidsbond"

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/davidsbond"

[[params.social]]
    name = "email"
    link = "davidsbond93@gmail.com"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Posts"
	url = "/posts"
	weight = 2

[[deployment.matchers]]
	pattern = "^.+\\.(js|css|svg|ttf)$"
	cacheControl = "max-age=31536000, no-transform, public"
	gzip = true

[[deployment.matchers]]
	pattern = "^.+\\.(png|jpg)$"
	cacheControl = "max-age=31536000, no-transform, public"
	gzip = false

[[deployment.matchers]]
	pattern = "^.+\\.(html|xml|json)$"
	gzip = true
